version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myquery
      POSTGRES_PASSWORD: chotipatpscp2024
      POSTGRES_DB: myquery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sakdithachpinkaew@gmail.com
      PGADMIN_DEFAULT_PASSWORD: chotipatpscp2024
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - postgres-network

volumes:
  pgdata:

networks:
  postgres-network:
